name: Lint & Test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: python:3.12-slim
    env:
      TEST_DB_USER: postgres
      TEST_DB_HOST: postgres
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          apt update && apt install build-essential -y
          pip install -r requirements-dev.txt
          pip install -e . 
          

      - name: Run Tests
        run: pytest

